:sparkles: [dev/xx10222] 계산기 1차 구현
selab-hs/selab-string-calculator pull request #15
Opened 2022-07-18 14:53 UTC by xx10222

- 최대한 객체의 책임을 생각하고, 예외처리도 고민하며 구현해봤습니다...
- 더 개선할 수 있을 것 같은데 지금은 더이상 생각이 안나서 호되게 코드리뷰로 혼내주시면 바아로 수정하겠슴둥!

2022-07-18 15:54 UTC, DongGeon0908 requested changes
몇가지 질문을 드립니다.

1) 객체지향은 무엇일까요?
2) 역할과 책임은 무엇일까요?
3) 해당 과제를 수행하면 가장 신경쓴 부분은 어디인가요??

객체지향 생활체조 원칙을 지키면서 리펙토링을 진행해보세요!

2022-07-18 15:54 UTC, DongGeon0908 commented on README.md
> +-
본인이 분석한 요구사항은????????????

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/CalculateStack.java
> +public class CalculateStack {
자료구조를 네이밍으로 쓰지 않습니다!

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/CalculateStack.java
> +    public double getStack(String input) throws Exception {
왜 Exception을 던질까요??

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +    }
해당 코드에서 뭔가 어색한 게 느껴지네요!
위에는 람다를 쓰는데, 밑에는 for문,,,

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        System.out.println(calculateStack.getStack(input));
Spring Application 클래스에 input내용이 있을까요?
현재 console로 구성된 부분을 web으로 바꿔끼면, 작동할까요??

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        System.out.println(calculateStack.getStack(input));
입력과 출력을 나눠주세요!

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/CalculateStack.java
> +        double first = Double.parseDouble(arr[0]);
클래스명칭은 자료구조를 사용했는데, 해당 비즈니스 로직에서는 자료구조를 사용하지 않았네요!!
자료구조를 잘쓰면 좋은 프로그램을 만들 수 있습니다

2022-07-18 15:54 UTC, DongGeon0908 commented on src/main/java/CalculateStack.java
> +        }
역할과 책임이란 건 무엇일까요?
객체지향은 무엇을 의미하는 걸까요?

2022-07-18 15:54 UTC, DongGeon0908 commented on README.md
> +-
가장 기본은 본인의 요구사항을 작성하는 것!

2022-07-18 15:54 UTC, DongGeon0908 commented on README.md
> +# SE-LAB CalculateStack
계산기라는 도메인을 생각해봤을때, 어떤 객체가 필요할까요?
계산기는 어떤 객체로 이뤄졌을까요???

2022-07-19 14:25 UTC, xx10222 commented on src/main/java/Operator.java
> +    }
if문 중괄호 쓰기, stream으로 쓰기

2022-07-19 14:26 UTC, xx10222 commented on src/main/java/CalculateStack.java
> +        }
숫자와 연산자가 만난다 -> 클래스 분리
calculate에서 2개의 클래스가 만나서 흘러가는 느낌 코드로 구현
하나의 메소드는 하나의 기능만을 갖도록 한다

2022-07-22 01:34 UTC, DongGeon0908 requested changes
static은 언제쓰는게 좋을까요?
일단 Calculator class에서는 static을 전부 빼고 진행하시죠

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/OutputStream.java
> +public class OutputStream {
Steam이라는 명칭은 네이밍에서 사용하지 않습니다!
네이밍을 정하는 것도 중요해용~

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +        }
.orElse chain을 걸면 밑에 if문이 사라질 것 같아요

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/InputStream.java
> +public class InputStream {
Stream이라는 명칭은 사용하지 않습니다

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +public class Calculator {
모든 메서드를 stataic하게 구성한 이유가 있을까요?
모든 메서드를 메모리로 관리해야 하는걸까요?

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
연산자인지 아닌지 확인하는 부분 같은데, 메서드 명칭이 어색하네요
Exception이 메서드명에 들어간게 이상해요

2022-07-22 01:34 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +        return num1;
Operator class에서 string값 받아서 연산자 찾아주는 로직을 만들 수 있을 것 같아요!

2022-08-01 05:02 UTC, DongGeon0908 requested changes
Calculator 클래스를 조금만 더 뿌셔봅시다!

2022-08-01 05:02 UTC, DongGeon0908 commented on README.md
>  ### 1. 요구사항
Good!

2022-08-01 05:02 UTC, DongGeon0908 commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.20'
지금은 lombok 없이 구현 부탁드려요!

2022-08-01 05:02 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +    }
해당 메서드가 없어도 될 것 같아요!

2022-08-01 05:02 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
Number라는 클래스를 하나 만들어서 관리하는 건 어떨까요?
지금 Operator는 빼서 관리하고 있는데, 숫자 객체는 해당 클래스에서 전부 조립하네요!

2022-08-01 05:03 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
이것이 숫자인지, 연산자인지 각각의 클래스에서 나눠주는 건 어떨까요?

2022-08-03 05:27 UTC, DongGeon0908 requested changes
Number class가 빠진 것 같아요! 
확인 부탁드립니다

2022-08-03 05:27 UTC, DongGeon0908 commented on README.md
>  ### 1. 요구사항
잘했어요

2022-08-03 05:27 UTC, DongGeon0908 commented on src/main/java/Operate.java
> +public interface Operate {
해당 인터페이스는 어디서 쓰시죠?

2022-08-03 05:27 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +public enum Operator {
좋아요 잘했어요

2022-08-03 05:27 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +        Queue<Number> numbers;
Number class는 어디에 있나요?

2022-08-03 09:06 UTC, DongGeon0908 requested changes

2022-08-03 09:06 UTC, DongGeon0908 commented on src/main/java/Number.java
> +        this.number = Double.parseDouble(number);
여기서 exception 터질 것 같은디

2022-08-03 09:06 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +
number 혹은 operator의 책임?

2022-08-04 12:25 UTC, xx10222 commented on src/main/java/Calculator.java
> +
나누기 연산자 예외 처리니까 Operator의 책임인 것 같습니다!

2022-08-14 05:29 UTC, DongGeon0908 approved these changes
접근제한자에 대해 공부해보시면 좋을 것 같습니다
문자열 계산기는 여기서 끝내시죠

2022-08-14 05:29 UTC, merged