[dev/twoosky] 계산기 구현
selab-hs/selab-string-calculator pull request #16
Opened 2022-07-20 17:00 UTC by twoosky

코드 리뷰 부탁드립니다 !!!!!!!!!!!
자바 열심히 공부하겠습니다. 맞을 준비 완료.
바쁜 와중에 코드 리뷰 감사합니다. 극락

2022-07-21 05:37 UTC, DongGeon0908 requested changes
고생하셨습니다!! 
리뷰 확인하시고, 질문에 답변 부탁드립니다!

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +    DIVIDE("/", (num1, num2) -> num1 / num2);
```suggestion
    DIVIDE("/", (num1, num2) -> num1 / num2),
    ;
```

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/InputUtil.java
> +    private static final Scanner sc = new Scanner(System.in);
```suggestion
    private static final Scanner scanner = new Scanner(System.in);
```

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        System.out.println(result);
input은 class로 따로 빼서 구현하셨는데, output은 왜 빼지 않았을까용?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +public class Calculator {
역할과 책임이란 무엇일까요?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
사용자가 입력한 데이터가 정말 숫자인지 연산자인지 어떻게 알 수 있을까요?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
그리고 숫자가 숫자인지, 연산자가 연산자인지 확인하는 건 각각의 역할과 책임이 아닐까요?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
이전에 올려드린 객체지향 생활체조 원칙을 지켜 수정 부탁드립니다!

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +}
계산기에서 모든 유효성을 검사하고 있는데, 해당 방법이 객체지향의 원칙에 부합할까요?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
자료구조를 사용한건 좋은 것 같아요!
그런데 분리하는 부분이 여기에 다있는게 맞을까요?

2022-07-21 05:37 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    private final LinkedList<String> operators;
연산자를 관리하는 클래스는 있는데, 숫자를 관리하는 클래스는 없네요

2022-07-21 05:37 UTC, DongGeon0908 commented on README.md
> +
해당 과제를 진행하면서, 고민한 점 그리고 설계를 어떻게 진행했는지도 작성 부탁드립니다!

2022-07-28 20:30 UTC, twoosky commented on README.md
> +
넵 추가하겠습니다.

2022-07-28 20:30 UTC, twoosky commented on src/main/java/Calculator.java
> +public class Calculator {
하나의 객체는 하나의 동작만의 책임을 갖는 것 입니다

2022-07-28 20:30 UTC, twoosky commented on src/main/java/Operator.java
> +                .anyMatch(op -> op.operator.equals(operator));
스트림 요소 중 적어도 한개 이상의 요소와 일치하는지 확인하는 메소드입니다. 

여기서는 입력받은 연산자가 enum의 상수 중에 존재한다면 옳은 연산자 입력값이라고 판단해 true를 반환합니다.

2022-07-28 20:37 UTC, twoosky commented on src/main/java/Operator.java
> +    Operator(String operator, BiFunction<Integer, Integer, Integer> expression) {
매개변수 2개와 리턴값의 타입을 받아 리턴값을 반환하는 함수형 인터페이스입니다. 

람다 표현식은 함수형 인터페이스를 인자로 받는 메서드에만 사용할 수 있어서 BiFunction을 사용했습니다

2022-07-28 20:37 UTC, twoosky commented on src/main/java/Main.java
> +        System.out.println(result);
리팩토링 진행하겠슴다!

2022-07-28 20:39 UTC, twoosky commented on src/main/java/Calculator.java
> +}
객체지향과는 거리가 먼 코드인거 같습니다.

2022-07-29 00:37 UTC, twoosky commented
코드 리뷰 감사합니다 !!!!!!!!! 극락 🫡

2022-07-29 01:22 UTC, DongGeon0908 requested changes
고생하셨습니다!!
객체지향 생활 체조 원칙을 지켜 코드를 수정해보세요

2022-07-29 01:22 UTC, DongGeon0908 commented on README.md
> +
readme에 작성해주세요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    public int calculate() {
객체지향 생활체조 원칙을 고려해서 진행해보세요!
지금은 하나의 메서드에서 여러 일을 하고 있네요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    }
메서드를 더 분리시킬 수 있을 것 같네요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Expression.java
> +@FunctionalInterface
해당 어노테이션에 대해 설명해주세요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +                .anyMatch(op -> op.operator.equals(operator));
2개의 메서드를 분리한 이유가 무엇일까요?
거의 비슷하게 동작하는 것 같아서요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +    private static final LinkedList<String> operators = new LinkedList<>();
해당 변수는 여기에 있는게 맞을까요?

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Operand.java
> +    private final LinkedList<Integer> operands;
```suggestion
    private final List<Integer> operands;
```

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Operand.java
> +    }
더 깔끔하게 하는 방법이 있을 것 같아요

2022-07-29 01:22 UTC, DongGeon0908 commented on src/main/java/Operand.java
> +    }
매개변수로 int를 넘겨주는 건 어떨까요?
왜 객체형 타입을 쓰신걸까요?

2022-07-29 08:39 UTC, luisjang-wt commented on src/main/java/Calculator.java
> +        String[] elements = input.split(" ");
공백으로 분리하고 있습니다 "1+ 2"가 input에 대입되면 오류가 발생할까요?

1. 메소드 작성시 단위테스트 코드도 함께 작성되면 좋을 것 같습니다.

2. 공백으로 분리하는것도 좋지만 정규식등을 활용해 연산자,괄호,수치등을 분리하면 좋을 것 같습니다.

-지나가던 선배 :)

2022-08-01 05:00 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +        String[] elements = input.split(" ");
리뷰 감사합니다!!
@twoosky 확인 부탁드려요~~!

2022-08-02 18:07 UTC, twoosky commented on src/main/java/Expression.java
> +@FunctionalInterface
@FunctionalInterface 어노테이션은 해당 인터페이스가 함수형 인터페이스 조건에 맞는지 검사해줍니다. 
함수형 인터페이스는 구현 해야 할 추상메소드가 하나만 정의된 인터페이스입니다.

2022-08-02 18:09 UTC, twoosky commented on src/main/java/Operator.java
> +                .anyMatch(op -> op.operator.equals(operator));
엇 그렇네요. getInstance() 메소드에서 유효성 검사와 인스턴스 반환을 모두 할 수 있을 거 같습니다.

2022-08-02 18:09 UTC, twoosky commented on src/main/java/Operator.java
> +    private static final LinkedList<String> operators = new LinkedList<>();
흠 이상한거 같아요. 좀 더 고민해보겠습니다.

2022-08-02 18:10 UTC, twoosky commented on src/main/java/Operand.java
> +    }
넵 !! 고민해보겠습니다.

2022-08-02 18:11 UTC, twoosky commented on src/main/java/Operand.java
> +    }
int와 Integer의 차이를 명확히 모르고 있었던거 같아요.
알맞은 타입으로 수정하겠습니다!

2022-08-02 18:12 UTC, twoosky commented on src/main/java/Calculator.java
> +        String[] elements = input.split(" ");
네 !! 리뷰감사합니다.

2022-08-06 13:11 UTC, DongGeon0908 reviewed
이번 과제는 넘어가도 될 것 같네요!!

2022-08-06 13:11 UTC, merged