Kihyun/working2
selab-hs/selab-string-calculator pull request #20
Opened 2022-08-15 13:23 UTC by KimKiHyun0206

드디어 제대로 PR 했습니다

2022-08-16 12:42 UTC, DongGeon0908 requested changes
고생하셨습니다 전부 리뷰드리는 것보다는 직접 고치는게 좋을 것 같아서, 중간정도까지만 리뷰 드렸습니다

1. static을 거의 모든 메서드에서 사용했는데, 이유가 있을까요? static은 어떻게 메모리가 관리되는지 학습해보세요!
2. 자바 코딩 컨벤션을 지켜주세요!! 파스칼, 카멜, 스네이크 등 다양한 표기법이 있습니다
3. 변수명, 클래스명에는 자료구조 명칭을 사용하지 않습니다
4. test class는 내가 만든 프로덕트 코드에 대한 테스트를 해야 합니다!
5. 객체의 역할과 책임에 대해 고민해보세요!! 내가 나임을 증명하는 것이 누구의 책임일지!

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/signtest/Sign.java
> +    private BiFunction<Integer, Integer, Integer> expression;
BiFunction이 어떤 일을 수행할까요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/signtest/Sign.java
> +    }
enum은 접근제한자가 필요 없나요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/signtest/Sign.java
> +public enum Sign {
Sign라는 명칭이 혼동을 주는 것 같네요
연산자는 Operator아닌가요?

해당 명칭을 정한 이유를 알려주세요

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/SIGNError.java
> +package Calculator.View.ExpressError;
패키지명은 소문자입니다
자바 컨벤션 확인 부탁드려요

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/SIGNError.java
> +public class SIGNError implements ExpressError {
클래스명은 파스칼 케이스를 따릅니다

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/SIGNError.java
> +    static public void errorAlert() {
static으로 가져간 이유가 있을까요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/LengthError.java
> +public class LengthError implements ExpressError {
static으로 만든 이유가 있을까요?
error로 log를 찍어주면 되는거 아닐가요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/ExpressError.java
> +}
인터페이스에 static한 메서드를 만든 이유가 있나요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressError/ExpressError.java
> +package Calculator.View.ExpressError;
패키지는 소문자

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressAnswer.java
> +package Calculator.View;
패키지는 소문자

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/View/ExpressAnswer.java
> +    static public void showAnswer(int answer){
static으로 선언한 이유가 있을까요?
static은 어디서 데이터를 관리할까요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/SIGN.java
> +}
테스트코드와 중복되네요
중복된 코드를 짠 이유가 있을까요?
테스트가 테스트가 아닌것 같네요

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/InputFormula.java
> +            System.out.println(e.getMessage());
error를 로깅하는데, 또 sout하고 있네요

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/InputFormula.java
> +            InputAndConversion.UserInputFormula(br.readLine().split(" "));
UserInputFormula -> userInputFormula

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/Formula.java
> +        return Integer.parseInt(formula.get(i));
String이 정말 숫자형태의 문자열인지 어떻게 알까요?

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/Formula.java
> +    static public void setFormula(List<String> setFormula) {
변수명에 자료구조 명칭을 사용하지 않습니다

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Model/Formula.java
> +    static List<String> formula = new ArrayList<>();
모든 메서드에 static을 쓰셨네요
static이 어디에 데이터를 저장하는지 확인 부탁드립니다!

2022-08-16 12:42 UTC, DongGeon0908 commented on src/test/java/Calculator/Controller/Validate/CheckSIGN.java
> +public class CheckSIGN implements CheckValidateData {
클래스명은 파스칼 표기법입니다

2022-08-16 14:26 UTC, DongGeon0908 commented
리뷰 사항 정리해두었어요

1. static을 거의 모든 메서드에서 사용했는데, 이유가 있을까요? static은 어떻게 메모리가 관리되는지 학습해보세요!
2. 자바 코딩 컨벤션을 지켜주세요!! 파스칼, 카멜, 스네이크 등 다양한 표기법이 있습니다
3. 변수명, 클래스명에는 자료구조 명칭을 사용하지 않습니다
4. test class는 내가 만든 프로덕트 코드에 대한 테스트를 해야 합니다!
5. 객체의 역할과 책임에 대해 고민해보세요!! 내가 나임을 증명하는 것이 누구의 책임일지!
6. 접근제한자란 무엇일까요?? 한번 찾아보시길
7. 읽기 쉬운 코드, 이해하기 쉬운 코드란 무엇일까요??


클래스를 나눌라고 하신점 매우 좋습니다!!
그런데, 너무 많이 나누다 보니, 역할과 책임이 무분별해진 것 같네요!!

내가 보기에 멋진 코드보다, 남이 보기에 쉬운 코드로 작성하시길 추천드립니다

2022-08-16 22:39 UTC, KimKiHyun0206 commented on src/test/java/Calculator/View/ExpressAnswer.java
> +    static public void showAnswer(int answer){
static으로 선언한 이유는 어차피 클래스가 하나만 만들어지기 때문에 객체를 생성하지 않고 바로 작성하려는 꼼수가 있었습니다. static은 JVM의  Static Area에 저장됩니다. 그리고 static으로 선언한 데이터는 메모리에 한 번 할당되면 프로그램이 종료될 때 해제됩니다.

2022-08-16 22:42 UTC, KimKiHyun0206 commented on src/test/java/Calculator/View/ExpressError/ExpressError.java
> +}
모든 메소드에 static을 붙여서 추상 메소드를 사용하지 않고 정적 메소드를 사용한 것 같습니다.

2022-08-16 22:44 UTC, KimKiHyun0206 commented on src/test/java/Calculator/Model/Formula.java
> +        return Integer.parseInt(formula.get(i));
그 메소드가 사용되기 전에 입력 받은 문자열을 자료형으로 만든 것을 가지고 입력한 숫자가 자료형의 홀수 번째에 있는지, 입력한 기호가 자료형의 짝수 번째에 있는지 등을 검사하기 때문에 i 가 홀수라면 오류가 나지 않습니다.

2022-09-03 06:30 UTC, DongGeon0908 requested changes
고생하셨습니다
객체의 역할과 책임은 무엇일까요?

특정 오브젝트(예를 들어 냉장고)가 어디까지 역할과 책임을 가져야 될까요???

나누는 건 좋지만, 나눈 결과가 절차지향적인 모습을 가지고 있네요!

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +        MainSequence.sequence();
계산기 클래스에서 해당 클래스가 시퀀스가 필요한 이유가 있나요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculateConfig.java
> +public class CalculateConfig {
Configuration이 자바에서 혹은 스프링에서 어떤역할로 쓰이는지 아실까요??

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculateLogic.java
> +public interface CalculateLogic {
계산하다는 Calculate 아닌가요??

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculationUsingSwitch.java
> +public class CalculationUsingSwitch implements CalculateLogic {
Switch 라는 자바 문법이 있는데 아실까요??

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculationUsingSwitch.java
> +    private int answer;
가변 객체와 불변 객체에 대해 설명해주세요

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculationUsingSwitch.java
> +    private void calculate(String sign, int number) {
Enum을 사용해보세요
혹은 추상클래스

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/calculatelogic/CalculationsUsingOperator.java
> +    static {
연산자 관련 클래스 하나에서 전부 처리 가능하지 않을까요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/inputlogic/InputBufferReader.java
> +public class InputBufferReader implements InputLogic{
불필요한 인터페이스는 지양!

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/inputlogic/InputConfig.java
> +public class InputConfig {
Config라는 클래스로 나눈 이유가 있나요
과도하게 나눈 것 같아요

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/inputlogic/InputScanner.java
> +        Scanner sc = new Scanner(System.in);
Scanner scanner

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/MainSequence.java
> +        validationConfig.validateSequence().order(retentionOfNecessaryDate.getFormula());
클래스를 계속 나누시 위해 노력하셨는데
결국에 해당 메서드에서 다 의존성 및 로직이 구현되어 있네요

의존성이란 무엇일까요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/SecondSequence.java
> +public class SecondSequence {
해당 인터페이스를 만들 이유가 있을까요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/validatesequence/ValidationConfig.java
> +public class ValidationConfig {
Config의 의미에 대해 한번 찾아보셔용

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/validatesequence/ValidationSequence.java
> +public interface ValidationSequence {
Sequence를 붙인 이유가 있나요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/validatesequence/ValidationSequenceOne.java
> +    ValidationCheckLogic length;
접근제한자는 어디있나요

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/sequencelogic/validatesequence/ValidationSequenceOne.java
> +    ValidationCheckLogic number;
변수명과 매치가되지 않아 코드를 읽기 어려워요

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/showconsole/ConsoleConfig.java
> +public class ConsoleConfig {
해당 클래스의 존재 이유에 대해 설명해주세요

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/showconsole/ErrorNotification.java
> +public class ErrorNotification implements ResultNotification{
Logger에 대해 아실까요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/storage/RetentionOfNecessaryDate.java
> +public class RetentionOfNecessaryDate {
계산기에서 필요한 도메인인가요?

2022-09-03 06:30 UTC, DongGeon0908 commented on src/main/java/storage/SignAnalysisAndCalculation.java
> +public enum SignAnalysisAndCalculation {
Enum을 만드셨군요
그런데 왜 다른 클래스들에서 계산로직이 계속 보이는 걸까요 ㅠㅠ

2022-09-03 06:59 UTC, KimKiHyun0206 commented on src/main/java/calculatelogic/CalculateConfig.java
> +public class CalculateConfig {
Configuration은 스프링에서 설정 파일을 만들기 위한 어노테이션 또는 Bean을 등록하기 위한 어노테이션입니다.

2022-09-06 01:29 UTC, KimKiHyun0206 commented on src/main/java/showconsole/ErrorNotification.java
> +public class ErrorNotification implements ResultNotification{
학습하겠습니다

2022-09-06 01:31 UTC, KimKiHyun0206 commented on src/main/java/calculatelogic/CalculationUsingSwitch.java
> +    private int answer;
불변 객체 : Java에서 Class의 인스턴스가 생성된 이후에 내부 상태를 변경할 수 없는 객체
가변 객체 : Java에서 Class의 인스턴스가 생성된 이후에 내부 상태가 변경 가능한 객체

2022-09-13 11:27 UTC, leeheefull reviewed
수고하셨습니다! 제 생각이 정답은 아닙니다. 이상하다 싶으면 반론 해주세요!

2022-09-13 11:27 UTC, leeheefull commented on src/main/java/showconsole/ErrorNotification.java
> +    String errorAlert;
필드 변수의 접근제한자를 private으로 하는게 좋을 것 같습니다!

2022-09-13 11:27 UTC, leeheefull commented on src/main/java/Calculator.java
> +        MainSequence.mainSequence.sequence();
전반적으로 정적 메서드를 사용했는데 이유가 궁금합니다!

2022-09-13 11:27 UTC, leeheefull commented on src/main/java/calculatelogic/CalculateConfig.java
> +    public static CalculateConfig calculateConfig = new CalculateConfig();
해당 부분은 없어도 될 것 같습니다!

2022-09-13 11:27 UTC, leeheefull commented on src/main/java/calculatelogic/CalculationsUsingOperator.java
> +    }
재사용성과 역할의 분리를 위해서 클래스를 분리하는 것은 어떨까요?

2022-09-13 11:27 UTC, leeheefull commented on src/main/java/showconsole/ErrorTypeClassification.java
> +}
개인적으로 해당 부분이 정적 메서드를 사용했을 때, 효과를 보고 있다고 생각합니다! bb

2022-09-13 11:27 UTC, leeheefull commented on src/test/java/validatelogic/NumberValidationTest.java
> +                .forEach(NumberValidationTest::notStartZero);
list는 stream으로 감싸지 않아도 forEach가 가능합니다!

2022-09-13 11:27 UTC, leeheefull commented on src/test/java/validatelogic/NumberValidationTest.java
> +    }
테스트 코드는 본인이 구현한 로직을 검증하는 것입니다.
위의 코드는 구현한 로직을 검증하지 않는 것으로 보입니다!

2022-09-17 02:44 UTC, KimKiHyun0206 commented on src/main/java/showconsole/ErrorNotification.java
> +    String errorAlert;
수정했습니다

2022-09-17 02:45 UTC, KimKiHyun0206 commented on src/main/java/Calculator.java
> +        MainSequence.mainSequence.sequence();
싱글톤 패턴을 적용해보고 싶어서 사용했습니다.

2022-09-21 12:54 UTC, leeheefull commented on src/main/java/Calculator.java
> +        MainSequence.mainSequence.sequence();
사실 싱글톤 패턴은 안티 패턴이라고 합니다
안티 패턴인 이유와 사용하면 적절할 경우를 찾아보시면 좋을 것 같아요

2022-09-21 13:57 UTC, leeheefull reviewed
제 의견을 말씀드리자면, 계산기의 전체적인 구조는 아래와 같습니다.

1. 계산기를 생각한다면 떠오르는 object는 숫자와 연산자입니다.
2. 그리고, 해당 요구사항에서 필요한 서비스는 문자열이 들어왔을 때, 숫자와 연산자를 구별하는 것입니다.
3. controller는 요구사항의 전반적인 흐름이 보여야합니다.

위의 세 가지를 고려하고 구현한다면 좋을 것 같습니다. 수고하셨습니다.

2022-09-21 13:57 UTC, leeheefull commented on src/main/java/model/MathStorage.java
> +            signs.add(formula.get(i));
중괄호는 빼지 않고 해주는게 좋습니다

2022-09-28 03:58 UTC, closed without merging

2022-09-28 03:58 UTC, KimKiHyun0206 commented
PR 닫기