(박창주) StringCalculator 리뷰 요청드립니다.
selab-hs/selab-string-calculator pull request #26
Opened 2023-05-10 05:35 UTC by ds4pae

(박창주) StringCalculator 리뷰 요청드립니다.

2023-05-10 14:51 UTC, DongGeon0908 requested changes
계산기는 어떻게 이뤄졌을까요?
쉽게 생각하면, 숫자와 연산자의 모임이지 않을까요?

그럼 숫자와 연산자는 각각 어떤 역할과 책임을 가져야 할까요?

리뷰드린 내용 및 https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93
해당 블로그에 있는 내용을 참고하여 수정 부탁드립니당

2023-05-10 14:51 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +    int[] inputNum;
여러번 연산을 진행해야 되는 경우라면, 해당 방법으로 진행했을 때 발생할 수 있는 문제는 무엇일까요?

2023-05-10 14:51 UTC, DongGeon0908 commented on src/main/java/Calc.java
> +                calcResult = calcResult / inputNum[i + 1];
for문안에 있는 if문을 매순간 전부 타야하는 이유가 있을가요?

2023-05-18 12:46 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +    int[] inputNum;
다른 패키지 혹은 클래스에서 접근을 제한합니다.
필요 시 상속하여 사용이 가능하도록 protected를 사용했습니다.
```java
protected String[] inputOperator;
protected int[] inputNum;
```

2023-05-18 12:52 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +            if (isNum(currentChar)) {
```java
else if(!currentChar.equals(" ")){
                System.out.println("잘못된 입력입니다. 프로그램을 종료합니다.");
                System.exit(0);
            }
``` 
연산자, 피연산자, 공백 외의 문자열이 들어오면 프로그램을 즉시 종료하게 수정했습니다.

2023-05-18 12:56 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +    }
코딩 도중에 놓친 부분인 것 같습니다.
이것 또한 상속 시 사용이 가능하도록 protected로 수정했습니다.
```java
 protected boolean isNum(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    protected boolean isOperator(String str) {
        return str.equals("+") || str.equals("-") || str.equals("*") || str.equals("/");
    }
```

2023-05-18 13:09 UTC, ds4pae commented on src/main/java/Calc.java
> +        System.out.println("결과값 : " + calcResult);
```java
public static void main(String[] args) {
        GetInputValue giv = new GetInputValue();
        CheckNumOperator checkNumOperator = new CheckNumOperator(giv.getInputValue());
        Calc calc = new Calc(checkNumOperator);
    }
``` 
수정해서 Main 깔끔하게 정리했습니다.
"입력은 클래스를 빼서 관리" 라는 말이 잘 이해가 되지 않아서 나름대로 해봤습니다.

2023-05-18 13:12 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +    int[] inputNum;
학교 과제를  제출하듯이 주어진 입력값과 출력값에만 집중해서 코드를 짯습니다.
여러번 연산 시에는 변수들이 초기화가 되지않아 문제가 생길 수 있을 것 같습니다.

```java
protected String[] inputOperator = { };
    protected int[] inputNum = { };
```

2023-05-18 13:21 UTC, ds4pae commented on src/main/java/Calc.java
> +                calcResult = calcResult / inputNum[i + 1];
```java
 if(checkNumOperator.inputOperator[i].equals("+"))
                calcResult = calcResult + checkNumOperator.inputNum[i + 1];
            else if(checkNumOperator.inputOperator[i].equals("-"))
                calcResult = calcResult - checkNumOperator.inputNum[i + 1];
            else if(checkNumOperator.inputOperator[i].equals("*"))
                calcResult = calcResult * checkNumOperator.inputNum[i + 1];
            else if(checkNumOperator.inputOperator[i].equals("/"))
                calcResult = calcResult / checkNumOperator.inputNum[i + 1];
``` 
위처럼 수정하였지만, inputOperator이 `"/"`으로 들어올 때 결국 앞의 if문은 전부 타야하기에 그리 효율적인 코드는 아니라고 생각은 됩니다.

2023-05-18 15:38 UTC, DongGeon0908 commented on src/main/java/Calc.java
> +        System.out.println("결과값 : " + calcResult);
입력은 별도의 클래스에 로직을 구현하셨는데,
출력은 왜 비즈니스 로직과 같이 있는 걸까요??

2023-05-18 15:38 UTC, DongGeon0908 commented on src/main/java/Calc.java
> +        System.out.println("결과값 : " + calcResult);
입출력과 비즈니스 로직을 분리해보시죠!

2023-05-18 15:40 UTC, DongGeon0908 requested changes
객체지향 생활체조를 적용해서 수정 부탁드립니다.

https://jamie95.tistory.com/99

2023-05-19 11:25 UTC, ds4pae commented on src/main/java/Calc.java
> +        System.out.println("결과값 : " + calcResult);
이해했습니다!
```java
 public static void main(String[] args) {
        GetInputValue giv = new GetInputValue();
        CheckNumOperator checkNumOperator = new CheckNumOperator(giv.getInputValue());
        Calc calc = new Calc();
        PrintResult printResult = new PrintResult(calc.Calc(checkNumOperator));
    }
``` 
PrintResult 클래스를 생성해서 출력을 분리했습니다.

2023-05-21 16:03 UTC, DongGeon0908 requested changes
객체의 관점에서 생각하면, 계산기는 **숫자와 연산자의 상호작용**일 것 같아요
그럼 여기서 숫자와 연산자 라는 객체를 만들어서 구현해보는 건 어떨가요?

2023-05-21 16:03 UTC, DongGeon0908 commented on src/main/java/Calc.java
> +            }
switch 문을 사용하지 않고 구현해보는 건 어떨까요?
Enum 혹은 추상클래스를 통한 연산자 로직 구현 등 다양한 방법이 있을 것 같아요

2023-05-24 01:22 UTC, DongGeon0908 requested changes
역할과 책임이 무엇인지 설명해주세요

2023-05-24 01:22 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +    protected int[] inputNum = { };
객체지향의 핵심요소는 역할과 책임입니다
연산자라는 객체를 통해 역할과 책임을 정의하였으니까, 다음으로는 숫자라는 객체에 대해 역할과 책임을 정의해보는게 어떨까요?

2023-05-30 01:08 UTC, DongGeon0908 requested changes
역할과 책임에 집중해주세요
메서드는 오직 하나의 일만 수행하도록 개선해주세요

객체지향의 사실과 오해 책을 읽어보세요

2023-05-30 01:08 UTC, DongGeon0908 commented on src/main/java/Number.java
> +    static int[] number = { };
static이면 계속 데이터가 쌓이는게 아닌가요??

일급객체와 일급컬렉션을 정리해주세요

2023-05-30 01:08 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +        return str.equals("+") || str.equals("-") || str.equals("*") || str.equals("/");
regex라는게 있어요
작용해보세요

2023-05-30 01:08 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +            return false;
실패한 로그를 남겨주세요

2023-05-30 01:08 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +            if (isNum(currentChar)) {
객체지향 생활체조 원칙을 지켜주세요

2023-05-31 07:36 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +            return false;
```java
protected boolean isNum(String str) {
        try {
            return str.matches("^[0-9]+$");
        } catch (NumberFormatException e) {
            return false;
        }
    }
``` 
isNum이 아닐경우 isOperator을 확인하고 isOperator 또한 아닌 경우에 checkBlank를 실행하도록 수정했습니다.
```java
 private boolean checkBlank(String currentChar) {
        if(currentChar.isBlank())
            return true;
        else{
            System.out.println("잘못된 입력입니다. 프로그램을 종료합니다.");
            System.exit(1);
            return false;
        }
    }
```

2023-05-31 07:38 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +        return str.equals("+") || str.equals("-") || str.equals("*") || str.equals("/");
```java
 protected boolean isOperator(String str) {
        String operatorPattern = "[+\\-*/]";
        if(Pattern.matches(operatorPattern, str)) return true;
        else return false;
    }
``` 
isNum 또한 정규표현식으로 수정했습니다.

2023-05-31 07:41 UTC, ds4pae commented on src/main/java/Number.java
> +    static int[] number = { };
```java
public static int getResult(Number number){
        int calcResult = number.number[0];
        for (int i = 0; i < CheckNumOperator.inputOperator.length; i++) {
            calcResult = Operator.calculate(CheckNumOperator.inputOperator[i], calcResult, number.number[i+1]);
        }
        return calcResult;
    }
``` 
이전에는 Number 클래스의 number값을 정적으로 가져와서 사용했는데, 수정 한 이후에는 CheckNumOperator의 inputNum값을 정적으로 가져와서 사용했습니다.
```java
public class CheckNumOperator {
    protected static String[] inputOperator = { };
    protected static Number inputNum;
```

2023-05-31 07:45 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +            if (isNum(currentChar)) {
아직 수정하고 싶은 부분이 많기도 하고 계속 수정하다 보니 원칙을 지키지 못하고 있는 것 같습니다.
원칙을 지키려고 시도해보고는 있습니다 T.T 노력하겠습니다

2023-06-18 06:54 UTC, DongGeon0908 requested changes
배열 대신, Collection을 사용하도록 수정해주세요.

2023-06-18 06:54 UTC, DongGeon0908 commented on src/main/java/Number.java
> +    int[] number = { };
접근 제한자 여부

2023-06-18 06:54 UTC, DongGeon0908 commented on src/main/java/CheckNumOperator.java
> +    private void countNumOperator(String[] tokens) {
해당 기능은 왜 필요한거에요?

2023-06-18 08:05 UTC, ds4pae commented on src/main/java/Number.java
> +    int[] number = { };
```
import java.util.regex.Pattern;
public class Number {
	+private int[] number = { };
```
private 접근 제한자를 사용했습니다.

2023-06-18 08:06 UTC, ds4pae commented on src/main/java/CheckNumOperator.java
> +    private void countNumOperator(String[] tokens) {
배열의 크기를 지정해주지 않다 보니 `ArrayIndexOutOfBoundsException` 이 발생해, 배열의 크기를 측정하는 `countNumOperator()`을 사용해 `inputNumber`과 `inputOperator`배열의 크기를 지정해주었습니다.

배열을 `Collection`으로 변경 할 시 `countNumOpeator()`은 따로 필요하지 않을 것 같습니다!

2023-06-18 10:17 UTC, ds4pae commented
> 배열 대신, Collection을 사용하도록 수정해주세요.https://github.com/selab-hs/selab-string-calculator/pull/26#pullrequestreview-1484989624
- Collection을 사용해야 하는 이유
    1. 정적 메모리 할당이 아닌 **동적 메모리 할당** (배열은 정적 메모리)
    2. 배열은 크기를 지정해주고 공간을 만든다면 컬렉션은 유동적으로 추가/삭제해줄 수 있다.       

```java
protected static String[] inputOperator;
protected static int[] inputNum;
->
protected static ArrayList<String> inputOperator;
protected static ArrayList<Integer> inputNum;
--------------------------------------------------
inputNum[numIndex] = Integer.parseInt(tokens[i]);
->
//오류가 납니다.(NullPointerException)
inputNum.add(Integer.parseInt(tokens[i]));
->
//오류는 안나는데 뭔가 답답합니다.
ArrayList<Integer> numList = new ArrayList<>();
numList.add(Integer.parseInt(tokens[i]));
inputNum = numList;
```

- `NullPointerException` 오류 해결 필요!
    - 해결은 했으나 `NullPointerException` 오류가 생기는 이유를 알 수 없었습니다
    - `inputNum` , `inputOperator` 둘 다 오류가 생김
        1. 초기화 되지 않아서 생기는 문제 or `.add()` 부분 문제

2023-06-28 13:37 UTC, merged