Add : String_Calculator 구현 완료
selab-hs/selab-string-calculator pull request #7
Opened 2021-12-04 11:13 UTC by F-UMI

디렉토리 및 클래스 설명 과 코멘트는 README.md 에 설명되어있습니다.

2021-12-04 13:04 UTC, leeheefull commented on src/main/java/Calculator.java
> +  private final static Progress PROGRESS = new Progress();
주로 대문자 변수명은 상수를 표현할 때 사용합니다.

객체 변수는 카멜케이스를 따릅니다.

2021-12-04 13:28 UTC, leeheefull commented on src/main/java/Calculator.java
> +          break;
`Enum`을 사용하면 `switch`문을 없앨 수 있습니다.

그리고 직접 구현하신 `Plus`, `Minus`, ... 등이 하는 기능도 함수형 인터페이스를 통해서 간단하게 구현할 수 있습니다.

2021-12-04 13:34 UTC, leeheefull commented on src/main/java/Calculator.java
> +  private final static Progress PROGRESS = new Progress();
`Progress` 객체의 변수를 `static`, `final`로 받으셨는데, 그 이유를 알 수 있을까요?

2021-12-04 13:41 UTC, leeheefull commented on src/main/java/Calculator.java
> +      int behindNumber = Integer.parseInt(inputs.get(BEHIND_NUMBER));
말씀처럼 다른 자료 구조를 사용하는 것을 추천드리겠습니다.

2021-12-04 13:42 UTC, leeheefull commented on src/main/java/Calculator.java
> +  }
말씀 드린 것처럼 자료구조를 바꾸면 보다 간단해 질 것 같습니다.

2021-12-04 13:43 UTC, leeheefull reviewed
처음인데 이렇게 클래스를 나눌 수 있다는게 대단하신 것 같습니다!! 수고하셨습니다.

2021-12-05 04:18 UTC, F-UMI commented on src/main/java/Calculator.java
> +  private final static Progress PROGRESS = new Progress();
progress의 `calculating` 메소드에 들어오는 데이터를 보호하려고 지정했었습니다.

2021-12-05 06:40 UTC, DongGeon0908 reviewed
고생하셨습니다!

처음인데 엄청나구만유!!

잘하셨어요!!

계산기에 어떤 객체가 더 들어갈 수 있는지 고민해보시면 좋을 것 같습니다!

2021-12-05 06:40 UTC, DongGeon0908 commented on src/main/java/Input.java
> +  private final static Scanner SCANNER = new Scanner(System.in);
여기서 Scanner 변수 명을 Scanner로 가져가는게 맞습니다!

2021-12-05 06:40 UTC, DongGeon0908 commented on src/main/java/Main.java
> +    System.out.println(calculator.isProgressing(input.scanLine(), INIT_RANGE));
input이 있다면 output class도 만드는게 좋을 것 같아요!

2021-12-05 06:40 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +  protected int isProgressing(List<String> inputs, int answer) {
Operator라는 객체를 만들어서 사용하셨는데,
숫자도 하나의 객체로 빼서 사용할 수 있지 않을까요?

2021-12-05 07:21 UTC, F-UMI commented on src/main/java/Calculator.java
> +  protected int isProgressing(List<String> inputs, int answer) {
어떻게 객체로서 적용시킬지 고민해보겠습니다!

2021-12-05 08:06 UTC, F-UMI commented
생각 외로 Number 객체 생성과 연관해서 다른 자료구조를 적용 시키는것에 어려움을 겪고 있습니다..!
그외 리뷰를 통해 수정가능한 부분에 대해 commit 진행하였습니다.

2021-12-11 05:10 UTC, F-UMI commented
그사이 따로 코드구현하면서 진행하려고 하는데 Numbers 하고 자료구조 바꾸는게 힘드네요.. 힌트를 얻고싶습니다!

2021-12-11 08:57 UTC, DongGeon0908 commented
윤섭님이 올려주신 코드 확인했습니다!
Operator 부분을 따로 빼서 진행하셨는데 좋은 것 같아요!
현재 숫자는 따로 객체로 관리되고 있지 않습니다!!

숫자 하나를 Number라는 객체로 가져가고, 다수의 Number를 가지는 List<Number>를 사용해보세요!

만약, 로직이 너무 길어지게 된다면 List<Number>를 가지는 Numbers라는 일급 컬렉션을 사용해보세요!

2021-12-11 11:00 UTC, F-UMI commented
말씀하신대로 Number 을 생성하는중 오늘은 시간이 다되어 중간에 멈춥니다. 
내일 마저 작성하겠습니다.

2021-12-12 10:19 UTC, F-UMI commented
![image](https://user-images.githubusercontent.com/54024213/145708549-f6c50f6c-41cb-4225-9d5e-7d89cc6740d6.png)   
* 말씀하신대로 일급컬렉션 생성하여 숫자를 리스트에 저장시키고 이를 계산 메소드에 이용되도록 클래스를 수정하였습니다.   
* 위 사진은 각 클래스들의 간략한 설명입니다.

2021-12-16 06:28 UTC, DongGeon0908 requested changes
Numbers를 만들어서 진행하는 건 좋아요!
그럼 Numbers에서 Number가지고 놀아야 된다고 생각합니다!

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Main.java
> +    output.printResult(calculator.isProgressing(input.scanLine(), INIT_RANGE));
한번에 하는 것보다는 나눠서 진행하는게 좋을 것 같아요~!!

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Numbers.java
> +public class Numbers {
Numbers는 Number라는 객체를 가지고 있는 일급 컬렉션으로서 사용되야 되다고 생각합니다!

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Numbers.java
> +  private final List<Integer> Numbers = new ArrayList<>();
Integer가 아니라 Number라는 객체가 들어가야 될 것 같네요!

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +  Operator(List<String> inputs) {
접근제한자가 없는 이뉴는 무엇일까요?

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Operators.java
> +    throw new RuntimeException();
stream으로 돌리는 건 어떨까요?

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Operators.java
> +    throw new RuntimeException();
exception을 ovveride한 클래스를 만들어보세요~

2021-12-16 06:28 UTC, DongGeon0908 commented on src/main/java/Input.java
> +    return new ArrayList<>(Arrays.asList(scanner.nextLine().split(REGEX)));
한줄로 진행하는 것도 좋지만 이렇게 길어지는 경우에는 한번 나누는게 좋아요!

2021-12-16 10:55 UTC, F-UMI commented on src/main/java/Operator.java
> +  Operator(List<String> inputs) {
직접 생성자를 작성하고 실수로 놓쳐버렸습니다! 수정하겠습니다.

2021-12-16 11:12 UTC, F-UMI commented on src/main/java/Numbers.java
> +public class Numbers {
일글 컬렉션에 대한 개념을 더 익히고 적용해보도록 하겠습니다!

2021-12-18 06:50 UTC, F-UMI commented on src/main/java/Operators.java
> +    throw new RuntimeException();
> stream으로 돌리는 건 어떨까요?

궁금한게 2가지 있습니다.
1. `Operator.value()`을 이용한 스트림을 만들게되면 `frontNumber `와 `behindNumber`를 `IntBinaryOperator.apply()` 로 전달하여 값을 `return`하려면 어떤 구문을 이용해야하나요?

2. 1번의 생각이 틀렸다면 결국은 `input_symbol`을 저장해놓는 `Operator`를 이용해 스트림을 생성하는데 
메소드를 어떻게 수정해야 할지 헷갈립니다.

2021-12-19 04:37 UTC, DongGeon0908 requested changes
화이팅~

2021-12-19 04:37 UTC, DongGeon0908 commented on src/main/java/Operators.java
> +    throw new RuntimeException();
operator는 validate가 된 상태의 숫자와 validate가 되지 않은 상태의 operator 연산자(String)를 받아서 계산 로직을 수행하게 됩니다!

그렇다면, operator의 집합을 돌리면서 input된(String operator) 값이 존재하는 지 찾고, 존재한다면 연산로직을 수행,
존재하지 않는다면 excpetion을 터트리면 됩니다!

2021-12-19 04:37 UTC, DongGeon0908 commented on src/main/java/Operators.java
> +    throw new RuntimeException();
<img width="177" alt="image" src="https://user-images.githubusercontent.com/50691225/146664034-06fd19ca-b15a-43fa-83dc-c81b53ee2cce.png">

2021-12-19 04:47 UTC, F-UMI commented
조언 감사합니다!

2021-12-19 17:31 UTC, DongGeon0908 requested changes
거의 끝나갑니다!! 조금 더 뽜이팅~

2021-12-19 17:31 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +public class Operator {
Operators라는 클래스가 String 값을 받아서 연산을 수행하게 됩니다!
그렇다면 이  클래스는 어떤 역학을 하는 걸까요?

이 클래스가 정말 필요할까요??

2021-12-19 17:32 UTC, DongGeon0908 commented
이제 어느정도 객체지향에 대해 감을 잡으신 것 같아요!
해당 repo에 있는 과제를 전부 수행하시면, 배웠던 것에 대한 회고를 작성해주세용~

2021-12-23 11:07 UTC, F-UMI commented
Number 객체의 활용에서 고민이 많아지고 있습니다
Numbers의 컬렉션을 생성하면서 제네릭타입으로 Number로 넘겼을때 제가 기존에 활용하려 했던 메소드의 반환값을 
제대로 활용하지 못하고 있는것 같습니다. 좀더 노력해보겠습니다!

2021-12-25 15:39 UTC, DongGeon0908 commented
확장성을 가지는 코드는 무엇일까요?
자바에서 확장성을 가지기 위해 사용되는 기술은 무엇일까요??
객체지향 스럽게 코드를 작성하기 위해서 우리는 무엇이 필요할까요??

저도 공부를 진행하면서 항상 고민했던 것 같아요!

1. SOLID
2. 인터페이스와 추상클래스
3. 각 오브젝트의 역할과 책임

윤섭님도 위의 개념을 한번 찾아보시길 추천드립니다!

2021-12-26 11:24 UTC, F-UMI commented
Slack에서 리뷰어 분들의 조언을 얻어 Numbers와 Operator 클래스를 사용하지 않은 상태로 구현 해보았습니다.
Number 객체를 사용하지 않은 이유는 위 두클래스를 사용하지 않는 것에 우선순위를 둬서 구현을 했기 때문입니다.
부대내 행사 관련된것으로 시간이 생각보다 많지 못하여 다음 커밋시 Number 클래스 생성하여 구문을 수정해보겠습니다. 혹여 제가 생각한 방안이 리뷰어분들이 알려주신것과 다를 수도 있기에 사용하지 않은 클래스는 주석화 처리만 해놓았습니다.

2021-12-26 12:29 UTC, darkant99 commented
전체적인 네이밍이 조금 더 명확하면 좋을것 같아요ㅎㅎ
군더더기 없는 코드 이지만 stream을 더 활용 해보시면 완벽한 코드가 될것 같아요!

2021-12-29 07:15 UTC, DongGeon0908 reviewed
Number 부분만 더 수정하시면 끝날 것 같습니다!
Number 객체로서 어떤 역할과 책임을 수행해야 될지 조금 더 고민하시면 될 것 같아요!

2021-12-29 07:15 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +        .ApplyOperand(frontOperand, Integer.parseInt(behindOperand));
메서드 네이밍 규칙을 변경해야 겠어요! 
앞에가 대문자라니~

2021-12-29 07:15 UTC, DongGeon0908 commented on src/main/java/Calculator.java
> +    return calculatedResult;
stream을 써보는 건 어떨까요?

2021-12-29 07:15 UTC, DongGeon0908 commented on src/main/java/Input.java
> +    List<String> InputData = Arrays.asList(scanner.nextLine().split(REGEX));
scanner.nextLine().split(REGEX)에서 한번 끊어주고, 그걸 return에서 list로 바꿔주는 방식이 조금 더 직관적일 것 같습니다!

2021-12-29 07:15 UTC, DongGeon0908 commented on src/main/java/Operator.java
> +  public int ApplyOperand(int frontOperand, int behindOperand) {
메서드명 변경하기!

2022-03-03 16:29 UTC, merged